### ISSUE TITLE
RuntimeError: memory access out of bounds

### ISSUE THREAD

**Issue by chidokun** [mljs/libsvm#16]
I have a big problem when loading a model string from file for the first run. libsvm can not deserialize model because of the following RuntimeError. But when I try training a dataset and then load my model from file, it's ok. 

```
RuntimeError: memory access out of bounds
    at wasm-function[84]:51
    at wasm-function[256]:11
    at SVM.Module._deserialize_model (D:\Documents\Thesis\sources\verizone-api\node_modules\libsvm-js\out\wasm\libsvm.js:79:107637)
    at ccall (D:\Documents\Thesis\sources\verizone-api\node_modules\libsvm-js\out\wasm\libsvm.js:79:4914)
    at D:\Documents\Thesis\sources\verizone-api\node_modules\libsvm-js\out\wasm\libsvm.js:79:5295
    at Function.load (D:\Documents\Thesis\sources\verizone-api\node_modules\libsvm-js\src\loadSVM.js:252:19)
    at Function.<anonymous> (D:\Documents\Thesis\sources\verizone-api\src\ml\MLModel.ts:17:30)
    at Generator.next (<anonymous>)
    at fulfilled (D:\Documents\Thesis\sources\verizone-api\src\ml\MLModel.ts:4:58)
```
Any solution?

**Comment by stropitek** [comment]
Hello @chidokun,

What exactly is the difference between the case that works and the one that doesn't?

Can you provide a model file and a code snippet that reproduces the error?

**Comment by AndreBreh** [comment]
i have the same error. The difference between the case that works and the one that doesn't is the file size.
I tested it with a serialized String of size 1,5mb and it works. Then i used a file with size 15mb and it doesnt work

**Comment by therealglazou** [comment]
I confirm this issue and the diagnostic above. Beyond a certain size, loading a model does not work any more. I'm unable to say if it's because serialization has generated an incorrect output or if it's a mem size issue on load. I would bet on the latter.
